openapi: 3.0.0
info:
  contact:
    email: support@datadoghq.com
    name: Datadog Support
    url: https://www.datadoghq.com/support/
  description: The Datadog API is an HTTP REST API. The API uses resource-oriented URLs to call the API, uses status codes to indicate the success or failure of requests, returns JSON from all requests, and uses standard HTTP response codes. Use the Datadog API to access the Datadog platform programmatically.
  title: Datadog Account Groups API
  version: '1.0'
servers:
- url: https://{subdomain}.{site}
  variables:
    site:
      default: datadoghq.com
      description: The regional site for Datadog customers.
      enum:
      - datadoghq.com
      - us3.datadoghq.com
      - us5.datadoghq.com
      - ap1.datadoghq.com
      - datadoghq.eu
      - ddog-gov.com
    subdomain:
      default: api
      description: The subdomain where the API is deployed.
- url: '{protocol}://{name}'
  variables:
    name:
      default: api.datadoghq.com
      description: Full site DNS name.
    protocol:
      default: https
      description: The protocol for accessing the API.
- url: https://{subdomain}.{site}
  variables:
    site:
      default: datadoghq.com
      description: Any Datadog deployment.
    subdomain:
      default: api
      description: The subdomain where the API is deployed.
security:
- apiKeyAuth: []
  appKeyAuth: []
tags:
- name: Groups
paths:
  /api/v2/scim/Groups:
    get:
      description: 'List groups in the organization.

        Results are paginated by `startIndex` and `count` parameters.

        Results can be narrowed down by the `filter` parameter.'
      operationId: ListSCIMGroups
      parameters:
      - description: Specifies the start index to fetch the results (1-indexed).
        in: query
        name: startIndex
        required: false
        schema:
          default: 1
          example: 1
          format: int64
          type: integer
        example: 1
      - description: Specifies the number of groups to be returned.
        in: query
        name: count
        required: false
        schema:
          default: 20
          example: 20
          format: int64
          type: integer
        example: 20
      - description: 'Specifies the url encoded filter to use to narrow down the results.

          Filters can be in the form of `displayName eq <group name>` or `externalId eq <external id of group>`

          or `id eq <group id> and members eq <user uuid>` or `members eq <user uuid> and id eq <group id>`.'
        in: query
        name: filter
        required: false
        schema:
          type: string
        example: example_value
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListExternalUserGroupResponse'
          description: OK
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
      security:
      - bearerAuth: []
      summary: Datadog List Groups
      tags:
      - Groups
      x-menu-order: 7
      x-permission:
        operator: AND
        permissions:
        - user_access_invite
        - user_access_manage
      x-undo:
        type: safe
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    post:
      description: 'Create a new group.

        The group may contain members.'
      operationId: CreateSCIMGroup
      requestBody:
        content:
          application/json:
            examples:
              json-request-body:
                value:
                  displayName: Group 1
                  externalId: group1
                  members:
                  - $ref: https://app.datadoghq.com/api/scim/v2/Users/d34a5f93-5690-4d3f-a293-f2ad5c7a82a4
                    display: John Doe
                    type: User
                    value: d34a5f93-5690-4d3f-a293-f2ad5c7a82a4
                  - $ref: https://app.datadoghq.com/api/scim/v2/Users/429ebce5-8ed3-4da9-9f1e-662f2dbc2fe6
                    display: Jane Doe
                    type: User
                    value: 429ebce5-8ed3-4da9-9f1e-662f2dbc2fe6
                  schemas:
                  - urn:ietf:params:scim:schemas:core:2.0:Group
            schema:
              $ref: '#/components/schemas/ExternalUserGroup'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalUserGroup'
          description: Created
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
      security:
      - bearerAuth: []
      summary: Datadog Create Group
      tags:
      - Groups
      x-menu-order: 8
      x-permission:
        operator: AND
        permissions:
        - user_access_invite
        - user_access_manage
      x-undo:
        operationId: DeleteSCIMGroup
        parameters:
        - name: group_id
          source: <RESPONSE_PATH>
        type: unsafe
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v2/scim/Groups/{group_id}:
    delete:
      description: Delete the group with the given `group_id`.
      operationId: DeleteSCIMGroup
      parameters:
      - description: None
        in: path
        name: group_id
        required: true
        schema:
          type: string
        example: abc-123-def
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
      security:
      - bearerAuth: []
      summary: Datadog Delete Group
      tags:
      - Groups
      x-menu-order: 12
      x-permission:
        operator: AND
        permissions:
        - user_access_invite
        - user_access_manage
      x-undo:
        type: idempotent
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    get:
      description: Get a single group using the `group_id`.
      operationId: GetSCIMGroup
      parameters:
      - description: None
        in: path
        name: group_id
        required: true
        schema:
          type: string
        example: abc-123-def
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalUserGroup'
          description: OK
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
      security:
      - bearerAuth: []
      summary: Datadog Get Group
      tags:
      - Groups
      x-menu-order: 9
      x-permission:
        operator: AND
        permissions:
        - user_access_invite
        - user_access_manage
      x-undo:
        type: safe
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    patch:
      description: Patch the group with the given `group_id`.
      operationId: PatchSCIMGroup
      parameters:
      - description: None
        in: path
        name: group_id
        required: true
        schema:
          type: string
        example: abc-123-def
      requestBody:
        content:
          application/json:
            examples:
              json-request-body:
                value:
                  Operations:
                  - op: replace
                    path: None
                    value:
                      displayName: Real new group
                      id: e43536e9-33fe-43f8-90b8-d3e39a7dd6ad
                  - op: add
                    path: None
                    value:
                      members:
                      - $ref: https://app.datadoghq.com/api/scim/v2/Users/f85e3868-ad7b-47e3-a8a9-ff1eade2bbf9
                        displayName: Bob Smith
                        value: f85e3868-ad7b-47e3-a8a9-ff1eade2bbf9
                  - op: remove
                    path: members[value eq "fddf0cf2-9b60-11ef-ad4b-d6754a54a839"]
                    value: null
                  schemas:
                  - urn:ietf:params:scim:api:messages:2.0:PatchOp
            schema:
              $ref: '#/components/schemas/ExternalUserGroupPatchRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalUserGroup'
          description: OK
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
      security:
      - bearerAuth: []
      summary: Datadog Patch Group
      tags:
      - Groups
      x-menu-order: 11
      x-permission:
        operator: AND
        permissions:
        - user_access_invite
        - user_access_manage
      x-undo:
        type: idempotent
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    put:
      description: Update the group with the given `group_id`.
      operationId: UpdateSCIMGroup
      parameters:
      - description: None
        in: path
        name: group_id
        required: true
        schema:
          type: string
        example: abc-123-def
      requestBody:
        content:
          application/json:
            examples:
              json-request-body:
                value:
                  displayName: Group 1
                  externalId: group1
                  id: e43536e9-33fe-43f8-90b8-d3e39a7dd6ad
                  members:
                  - $ref: https://app.datadoghq.com/api/scim/v2/Users/d34a5f93-5690-4d3f-a293-f2ad5c7a82a4
                    display: John Doe
                    type: User
                    value: d34a5f93-5690-4d3f-a293-f2ad5c7a82a4
                  - $ref: https://app.datadoghq.com/api/scim/v2/Users/429ebce5-8ed3-4da9-9f1e-662f2dbc2fe6
                    display: Jane Doe
                    type: User
                    value: 429ebce5-8ed3-4da9-9f1e-662f2dbc2fe6
                  schemas:
                  - urn:ietf:params:scim:schemas:core:2.0:Group
            schema:
              $ref: '#/components/schemas/ExternalUserGroup'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalUserGroup'
          description: OK
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '409':
          $ref: '#/components/responses/ConflictResponse'
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
      security:
      - bearerAuth: []
      summary: Datadog Update Group
      tags:
      - Groups
      x-menu-order: 10
      x-permission:
        operator: AND
        permissions:
        - user_access_invite
        - user_access_manage
      x-undo:
        type: idempotent
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v2/sensitive-data-scanner/config:
    get:
      description: List all the Scanning groups in your organization.
      operationId: ListScanningGroups
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensitiveDataScannerGetConfigResponse'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIErrorResponse'
          description: Bad Request
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIErrorResponse'
          description: Authentication Error
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
      summary: Datadog List Scanning Groups
      tags:
      - Groups
      x-given:
        configuration:
          step: a valid "configuration" in the system
      x-menu-order: 1
      x-permission:
        operator: OR
        permissions:
        - data_scanner_read
      x-undo:
        type: safe
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    patch:
      description: Reorder the list of groups.
      operationId: ReorderScanningGroups
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SensitiveDataScannerConfigRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensitiveDataScannerReorderGroupsResponse'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIErrorResponse'
          description: Bad Request
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIErrorResponse'
          description: Authentication Error
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
      summary: Datadog Reorder Groups
      tags:
      - Groups
      x-codegen-request-body-name: body
      x-menu-order: 2
      x-permission:
        operator: OR
        permissions:
        - data_scanner_write
      x-undo:
        type: idempotent
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v2/sensitive-data-scanner/config/groups:
    post:
      description: 'Create a scanning group.

        The request MAY include a configuration relationship.

        A rules relationship can be omitted entirely, but if it is included it MUST be

        null or an empty array (rules cannot be created at the same time).

        The new group will be ordered last within the configuration.'
      operationId: CreateScanningGroup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SensitiveDataScannerGroupCreateRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensitiveDataScannerCreateGroupResponse'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIErrorResponse'
          description: Bad Request
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIErrorResponse'
          description: Authentication Error
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
      summary: Datadog Create Scanning Group
      tags:
      - Groups
      x-codegen-request-body-name: body
      x-given:
        group:
          parameters:
          - name: body
            value: "{\n  \"data\": {\n    \"type\": \"sensitive_data_scanner_group\",\n    \"attributes\": {\n      \"name\": \"my-test-group\",\n      \"is_enabled\": false,\n      \"product_list\": [\n          \"logs\"\n      ],\n      \"filter\": {\n          \"query\": \"*\"\n      }\n    },\n    \"relationships\": {\n      \"configuration\": {\n        \"data\": {\n          \"id\": \"{{ configuration.data.id }}\",\n          \"type\": \"{{ configuration.data.type }}\"\n        }\n      },\n      \"rules\": {\n          \"data\": []\n      }\n    }\n  },\n  \"meta\": {}\n}"
          step: there is a valid "scanning_group" in the system
      x-menu-order: 4
      x-permission:
        operator: OR
        permissions:
        - data_scanner_write
      x-undo:
        operationId: DeleteScanningGroup
        parameters:
        - name: group_id
          source: data.id
        - name: body
          template: "{\n  \"meta\": {}\n}"
        type: unsafe
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v2/sensitive-data-scanner/config/groups/{group_id}:
    delete:
      description: Delete a given group.
      operationId: DeleteScanningGroup
      parameters:
      - $ref: '#/components/parameters/SensitiveDataScannerGroupID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SensitiveDataScannerGroupDeleteRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensitiveDataScannerGroupDeleteResponse'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIErrorResponse'
          description: Bad Request
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIErrorResponse'
          description: Authentication Error
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
      summary: Datadog Delete Scanning Group
      tags:
      - Groups
      x-codegen-request-body-name: body
      x-menu-order: 6
      x-permission:
        operator: OR
        permissions:
        - data_scanner_write
      x-undo:
        type: idempotent
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    patch:
      description: 'Update a group, including the order of the rules.

        Rules within the group are reordered by including a rules relationship. If the rules

        relationship is present, its data section MUST contain linkages for all of the rules

        currently in the group, and MUST NOT contain any others.'
      operationId: UpdateScanningGroup
      parameters:
      - $ref: '#/components/parameters/SensitiveDataScannerGroupID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SensitiveDataScannerGroupUpdateRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensitiveDataScannerGroupUpdateResponse'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIErrorResponse'
          description: Bad Request
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIErrorResponse'
          description: Authentication Error
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
      summary: Datadog Update Scanning Group
      tags:
      - Groups
      x-codegen-request-body-name: body
      x-menu-order: 5
      x-permission:
        operator: OR
        permissions:
        - data_scanner_write
      x-undo:
        type: idempotent
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    ExternalUserGroup:
      description: Definition of a group.
      properties:
        displayName:
          description: A human-readable name for the group.
          type: string
          example: Example Monitor
        externalId:
          description: An identifier for the resource as defined by the provisioning client.
          type: string
          example: abc-123-def
        id:
          description: The identifier of the resource. Not required when creating a group.
          type: string
          example: abc-123-def
        members:
          description: Members of the group.
          items:
            $ref: '#/components/schemas/ExternalUserGroupMembersItems'
          type: array
        meta:
          $ref: '#/components/schemas/ExternalUserGroupMeta'
        schemas:
          description: Input JSON Schemas.
          example:
          - urn:ietf:params:scim:schemas:core:2.0:Group
          items:
            type: string
          type: array
      type: object
    ListExternalUserGroupResponseResourcesItems:
      description: Resources returned in response to a List groups request.
      properties:
        displayName:
          description: A human-readable name for the group.
          example: My test group
          type: string
        externalId:
          description: An identifier for the resource as defined by the provisioning client.
          example: 346af543-e5ab-4855-937d-133231cd59ed
          type: string
        id:
          description: The identifier of the resource. Not required when creating a group.
          example: 0e80d350-9519-4771-9aa8-ce849fc36c20
          type: string
        members:
          description: A list of members belonging to the team.
          items:
            $ref: '#/components/schemas/ListExternalUserGroupResponseResourcesItemsMembersItems'
          type: array
        meta:
          $ref: '#/components/schemas/ExternalUserGroupMeta'
        schemas:
          description: Group JSON Schemas.
          example:
          - urn:ietf:params:scim:schemas:core:2.0:Group
          items:
            type: string
          type: array
      type: object
    SensitiveDataScannerStandardPatternData:
      description: A standard pattern.
      properties:
        data:
          $ref: '#/components/schemas/SensitiveDataScannerStandardPattern'
      type: object
    SensitiveDataScannerReorderConfig:
      description: Data related to the reordering of scanning groups.
      properties:
        id:
          description: ID of the configuration.
          type: string
          example: abc-123-def
        relationships:
          $ref: '#/components/schemas/SensitiveDataScannerConfigurationRelationships'
        type:
          $ref: '#/components/schemas/SensitiveDataScannerConfigurationType'
      type: object
    SensitiveDataScannerStandardPattern:
      description: Data containing the standard pattern id.
      properties:
        id:
          description: ID of the standard pattern.
          type: string
          example: abc-123-def
        type:
          $ref: '#/components/schemas/SensitiveDataScannerStandardPatternType'
      type: object
    ExternalUserGroupMeta:
      description: Metadata associated with a group.
      properties:
        created:
          description: The date and time the group was created.
          example: '2024-10-17T12:53:35.793Z'
          format: date-time
          type: string
        lastModified:
          description: The date and time the group was last changed.
          example: '2024-10-19T12:53:35.793Z'
          format: date-time
          type: string
        location:
          description: URL identifying the resource.
          example: https://app.datadoghq.com/api/scim/v2/Groups/429ebce5-8ed3-4da9-9f1e-662f2dbc2fe6
          type: string
        resourceType:
          description: Type of resource.
          example: Group
          type: string
      type: object
    SensitiveDataScannerGroupUpdateResponse:
      description: Update group response.
      properties:
        meta:
          $ref: '#/components/schemas/SensitiveDataScannerMetaVersionOnly'
      type: object
    SensitiveDataScannerConfiguration:
      description: A Sensitive Data Scanner configuration.
      properties:
        id:
          description: ID of the configuration.
          type: string
          example: abc-123-def
        type:
          $ref: '#/components/schemas/SensitiveDataScannerConfigurationType'
      type: object
    SensitiveDataScannerConfigurationData:
      description: A Sensitive Data Scanner configuration data.
      properties:
        data:
          $ref: '#/components/schemas/SensitiveDataScannerConfiguration'
      type: object
    SensitiveDataScannerGroupData:
      description: A scanning group data.
      properties:
        data:
          $ref: '#/components/schemas/SensitiveDataScannerGroup'
      type: object
    SensitiveDataScannerGroupDeleteResponse:
      description: Delete group response.
      properties:
        meta:
          $ref: '#/components/schemas/SensitiveDataScannerMetaVersionOnly'
      type: object
    SensitiveDataScannerReorderGroupsResponse:
      description: Group reorder response.
      properties:
        meta:
          $ref: '#/components/schemas/SensitiveDataScannerMeta'
      type: object
    SensitiveDataScannerGroupList:
      description: List of groups, ordered.
      properties:
        data:
          description: List of groups. The order is important.
          items:
            $ref: '#/components/schemas/SensitiveDataScannerGroupItem'
          type: array
      type: object
    ExternalUserGroupMembersItems:
      description: The definition of a member belonging to a group.
      properties:
        $ref:
          description: The URI corresponding to a SCIM resource that is a member of this group.
          example: https://app.datadoghq.com/api/scim/v2/Users/429ebce5-8ed3-4da9-9f1e-662f2dbc2fe6
          type: string
        display:
          description: A human-readable name for the group member.
          example: John Doe
          type: string
        type:
          description: A label indicating the type of resource.
          example: User
          type: string
        value:
          description: The identifier of the member of this group.
          example: 429ebce5-8ed3-4da9-9f1e-662f2dbc2fe6
          type: string
      type: object
    SensitiveDataScannerMetaVersionOnly:
      description: Meta payload containing information about the API.
      properties:
        version:
          description: Version of the API (optional).
          example: 0
          format: int64
          minimum: 0
          type: integer
      type: object
    SensitiveDataScannerGroupUpdateRequest:
      description: Update group request.
      properties:
        data:
          $ref: '#/components/schemas/SensitiveDataScannerGroupUpdate'
        meta:
          $ref: '#/components/schemas/SensitiveDataScannerMetaVersionOnly'
      required:
      - data
      - meta
      type: object
    SensitiveDataScannerMeta:
      description: Meta response containing information about the API.
      properties:
        count_limit:
          description: Maximum number of scanning rules allowed for the org.
          format: int64
          type: integer
          example: 42
        group_count_limit:
          description: Maximum number of scanning groups allowed for the org.
          format: int64
          type: integer
          example: 42
        has_highlight_enabled:
          default: true
          deprecated: true
          description: (Deprecated) Whether or not scanned events are highlighted in Logs or RUM for the org.
          type: boolean
          example: true
        has_multi_pass_enabled:
          deprecated: true
          description: (Deprecated) Whether or not scanned events have multi-pass enabled.
          type: boolean
          example: true
        is_pci_compliant:
          description: Whether or not the org is compliant to the payment card industry standard.
          type: boolean
          example: true
        version:
          description: Version of the API.
          example: 0
          format: int64
          minimum: 0
          type: integer
      type: object
    SensitiveDataScannerGroupIncludedItem:
      description: A Scanning Group included item.
      properties:
        attributes:
          $ref: '#/components/schemas/SensitiveDataScannerGroupAttributes'
        id:
          description: ID of the group.
          type: string
          example: abc-123-def
        relationships:
          $ref: '#/components/schemas/SensitiveDataScannerGroupRelationships'
        type:
          $ref: '#/components/schemas/SensitiveDataScannerGroupType'
      type: object
    SensitiveDataScannerRuleData:
      description: Rules included in the group.
      properties:
        data:
          description: Rules included in the group. The order is important.
          items:
            $ref: '#/components/schemas/SensitiveDataScannerRule'
          type: array
      type: object
    SensitiveDataScannerCreateGroupResponse:
      description: Create group response.
      properties:
        data:
          $ref: '#/components/schemas/SensitiveDataScannerGroupResponse'
        meta:
          $ref: '#/components/schemas/SensitiveDataScannerMetaVersionOnly'
      type: object
    SensitiveDataScannerGroupAttributes:
      description: Attributes of the Sensitive Data Scanner group.
      properties:
        description:
          description: Description of the group.
          type: string
          example: example_value
        filter:
          $ref: '#/components/schemas/SensitiveDataScannerFilter'
        is_enabled:
          description: Whether or not the group is enabled.
          type: boolean
          example: true
        name:
          description: Name of the group.
          type: string
          example: Example Monitor
        product_list:
          description: List of products the scanning group applies.
          items:
            $ref: '#/components/schemas/SensitiveDataScannerProduct'
          type: array
      type: object
    APIErrorResponse:
      description: API error response.
      properties:
        errors:
          description: A list of errors.
          example:
          - Bad Request
          items:
            description: A list of items.
            example: Bad Request
            type: string
          type: array
      required:
      - errors
      type: object
    SensitiveDataScannerRuleAttributes:
      description: Attributes of the Sensitive Data Scanner rule.
      properties:
        description:
          description: Description of the rule.
          type: string
          example: example_value
        excluded_namespaces:
          description: Attributes excluded from the scan. If namespaces is provided, it has to be a sub-path of the namespaces array.
          example:
          - admin.name
          items:
            type: string
          type: array
        included_keyword_configuration:
          $ref: '#/components/schemas/SensitiveDataScannerIncludedKeywordConfiguration'
        is_enabled:
          description: Whether or not the rule is enabled.
          type: boolean
          example: true
        name:
          description: Name of the rule.
          type: string
          example: Example Monitor
        namespaces:
          description: 'Attributes included in the scan. If namespaces is empty or missing, all attributes except excluded_namespaces are scanned.

            If both are missing the whole event is scanned.'
          example:
          - admin
          items:
            type: string
          type: array
        pattern:
          description: Not included if there is a relationship to a standard pattern.
          type: string
          example: example_value
        priority:
          description: Integer from 1 (high) to 5 (low) indicating rule issue severity.
          format: int64
          maximum: 5
          minimum: 1
          type: integer
          example: 42
        tags:
          description: List of tags.
          items:
            type: string
          type: array
        text_replacement:
          $ref: '#/components/schemas/SensitiveDataScannerTextReplacement'
      type: object
    SensitiveDataScannerTextReplacementType:
      default: none
      description: 'Type of the replacement text. None means no replacement.

        hash means the data will be stubbed. replacement_string means that

        one can chose a text to replace the data. partial_replacement_from_beginning

        allows a user to partially replace the data from the beginning, and

        partial_replacement_from_end on the other hand, allows to replace data from

        the end.'
      enum:
      - none
      - hash
      - replacement_string
      - partial_replacement_from_beginning
      - partial_replacement_from_end
      type: string
      x-enum-varnames:
      - NONE
      - HASH
      - REPLACEMENT_STRING
      - PARTIAL_REPLACEMENT_FROM_BEGINNING
      - PARTIAL_REPLACEMENT_FROM_END
    SensitiveDataScannerRuleRelationships:
      description: Relationships of a scanning rule.
      properties:
        group:
          $ref: '#/components/schemas/SensitiveDataScannerGroupData'
        standard_pattern:
          $ref: '#/components/schemas/SensitiveDataScannerStandardPatternData'
      type: object
    SensitiveDataScannerStandardPatternType:
      default: sensitive_data_scanner_standard_pattern
      description: Sensitive Data Scanner standard pattern type.
      enum:
      - sensitive_data_scanner_standard_pattern
      example: sensitive_data_scanner_standard_pattern
      type: string
      x-enum-varnames:
      - SENSITIVE_DATA_SCANNER_STANDARD_PATTERN
    SensitiveDataScannerGroupType:
      default: sensitive_data_scanner_group
      description: Sensitive Data Scanner group type.
      enum:
      - sensitive_data_scanner_group
      example: sensitive_data_scanner_group
      type: string
      x-enum-varnames:
      - SENSITIVE_DATA_SCANNER_GROUP
    SensitiveDataScannerGroupRelationships:
      description: Relationships of the group.
      properties:
        configuration:
          $ref: '#/components/schemas/SensitiveDataScannerConfigurationData'
        rules:
          $ref: '#/components/schemas/SensitiveDataScannerRuleData'
      type: object
    SensitiveDataScannerGroupResponse:
      description: Response data related to the creation of a group.
      properties:
        attributes:
          $ref: '#/components/schemas/SensitiveDataScannerGroupAttributes'
        id:
          description: ID of the group.
          type: string
          example: abc-123-def
        relationships:
          $ref: '#/components/schemas/SensitiveDataScannerGroupRelationships'
        type:
          $ref: '#/components/schemas/SensitiveDataScannerGroupType'
      type: object
    ExternalUserGroupPatchRequestOperationsItemsOp:
      description: The operation to be performed.
      enum:
      - add
      - replace
      - remove
      type: string
      x-enum-varnames:
      - ADD
      - REPLACE
      - REMOVE
    SensitiveDataScannerGetConfigResponse:
      description: Get all groups response.
      properties:
        data:
          $ref: '#/components/schemas/SensitiveDataScannerGetConfigResponseData'
        included:
          $ref: '#/components/schemas/SensitiveDataScannerGetConfigIncludedArray'
        meta:
          $ref: '#/components/schemas/SensitiveDataScannerMeta'
      type: object
    SensitiveDataScannerIncludedKeywordConfiguration:
      description: 'Object defining a set of keywords and a number of characters that help reduce noise.

        You can provide a list of keywords you would like to check within a defined proximity of the matching pattern.

        If any of the keywords are found within the proximity check, the match is kept.

        If none are found, the match is discarded.'
      properties:
        character_count:
          description: 'The number of characters behind a match detected by Sensitive Data Scanner to look for the keywords defined.

            `character_count` should be greater than the maximum length of a keyword defined for a rule.'
          example: 30
          format: int64
          maximum: 50
          minimum: 1
          type: integer
        keywords:
          description: 'Keyword list that will be checked during scanning in order to validate a match.

            The number of keywords in the list must be less than or equal to 30.'
          example:
          - credit card
          - cc
          items:
            type: string
          type: array
        use_recommended_keywords:
          description: 'Should the rule use the underlying standard pattern keyword configuration. If set to `true`, the rule must be tied

            to a standard pattern. If set to `false`, the specified keywords and `character_count` are applied.'
          type: boolean
          example: true
      required:
      - keywords
      - character_count
      type: object
    SensitiveDataScannerConfigurationType:
      default: sensitive_data_scanner_configuration
      description: Sensitive Data Scanner configuration type.
      enum:
      - sensitive_data_scanner_configuration
      example: sensitive_data_scanner_configuration
      type: string
      x-enum-varnames:
      - SENSITIVE_DATA_SCANNER_CONFIGURATIONS
    ExternalUserGroupPatchRequest:
      description: Request object for patching a group.
      properties:
        Operations:
          description: A list of update operations to be performed on a group.
          items:
            $ref: '#/components/schemas/ExternalUserGroupPatchRequestOperationsItems'
          type: array
        schemas:
          description: Input JSON Schemas
          example:
          - urn:ietf:params:scim:api:messages:2.0:PatchOp
          items:
            type: string
          type: array
      type: object
    SensitiveDataScannerGroupCreateRequest:
      description: Create group request.
      properties:
        data:
          $ref: '#/components/schemas/SensitiveDataScannerGroupCreate'
        meta:
          $ref: '#/components/schemas/SensitiveDataScannerMetaVersionOnly'
      type: object
    SensitiveDataScannerGetConfigResponseData:
      description: Response data related to the scanning groups.
      properties:
        attributes:
          additionalProperties: {}
          description: Attributes of the Sensitive Data configuration.
          type: object
        id:
          description: ID of the configuration.
          type: string
          example: abc-123-def
        relationships:
          $ref: '#/components/schemas/SensitiveDataScannerConfigurationRelationships'
        type:
          $ref: '#/components/schemas/SensitiveDataScannerConfigurationType'
      type: object
    SensitiveDataScannerGroupCreate:
      description: Data related to the creation of a group.
      properties:
        attributes:
          $ref: '#/components/schemas/SensitiveDataScannerGroupAttributes'
        relationships:
          $ref: '#/components/schemas/SensitiveDataScannerGroupRelationships'
        type:
          $ref: '#/components/schemas/SensitiveDataScannerGroupType'
      required:
      - type
      - attributes
      type: object
    SensitiveDataScannerProduct:
      default: logs
      description: Datadog product onto which Sensitive Data Scanner can be activated.
      enum:
      - logs
      - rum
      - events
      - apm
      type: string
      x-enum-varnames:
      - LOGS
      - RUM
      - EVENTS
      - APM
    ListExternalUserGroupResponse:
      description: List groups response object.
      example:
        Resources:
        - displayName: Group 1
          externalId: group1
          id: e43536e9-33fe-43f8-90b8-d3e39a7dd6ad
          members:
          - $ref: https://app.datadoghq.com/api/scim/v2/Users/d34a5f93-5690-4d3f-a293-f2ad5c7a82a4
            display: John Doe
            type: User
            value: d34a5f93-5690-4d3f-a293-f2ad5c7a82a4
          - $ref: https://app.datadoghq.com/api/scim/v2/Users/429ebce5-8ed3-4da9-9f1e-662f2dbc2fe6
            display: Jane Doe
            type: User
            value: 429ebce5-8ed3-4da9-9f1e-662f2dbc2fe6
          meta:
            created: '2024-11-22T15:05:52.055138963Z'
            lastModified: '2024-11-22T15:05:52.055139017Z'
            location: https://app.datadoghq.com/api/scim/v2/Groups/e43536e9-33fe-43f8-90b8-d3e39a7dd6ad
            resourceType: Group
          schemas:
          - urn:ietf:params:scim:schemas:core:2.0:Group
        - displayName: Group 2
          externalId: group2
          id: 79ef0d28-f257-4829-97e6-d23d2a26cb1a
          members:
          - $ref: https://app.datadoghq.com/api/scim/v2/Users/29da9fb7-8fca-4e87-bf58-86652253deae
            display: Alice Smith
            type: User
            value: 29da9fb7-8fca-4e87-bf58-86652253deae
          - $ref: https://app.datadoghq.com/api/scim/v2/Users/f85e3868-ad7b-47e3-a8a9-ff1eade2bbf9
            display: Bob Smith
            type: User
            value: f85e3868-ad7b-47e3-a8a9-ff1eade2bbf9
          meta:
            created: '2024-11-22T15:05:52.055139748Z'
            lastModified: '2024-11-22T15:05:52.055139813Z'
            location: https://app.datadoghq.com/api/scim/v2/Groups/79ef0d28-f257-4829-97e6-d23d2a26cb1a
            resourceType: Group
          schemas:
          - urn:ietf:params:scim:schemas:core:2.0:Group
        itemsPerPage: 2
        schemas:
        - urn:ietf:params:scim:api:messages:2.0:ListResponse
        startIndex: 1
        totalResults: 2
      properties:
        Resources:
          description: List of groups matching the request criteria.
          items:
            $ref: '#/components/schemas/ListExternalUserGroupResponseResourcesItems'
          type: array
        itemsPerPage:
          description: Number of groups returned per page.
          format: int64
          maximum: 4294967295
          minimum: 0
          type: integer
          example: 42
        schemas:
          description: List response JSON Schemas.
          example:
          - urn:ietf:params:scim:api:messages:2.0:ListResponse
          items:
            type: string
          type: array
        startIndex:
          description: Starting index of the groups for this page (1-indexed).
          format: int64
          maximum: 4294967295
          minimum: 0
          type: integer
          example: 42
        totalResults:
          description: Total number of groups matching the request criteria.
          format: int64
          maximum: 4294967295
          minimum: 0
          type: integer
          example: 42
      type: object
    SensitiveDataScannerConfigRequest:
      description: Group reorder request.
      properties:
        data:
          $ref: '#/components/schemas/SensitiveDataScannerReorderConfig'
        meta:
          $ref: '#/components/schemas/SensitiveDataScannerMetaVersionOnly'
      required:
      - data
      - meta
      type: object
    SensitiveDataScannerGroup:
      description: A scanning group.
      properties:
        id:
          description: ID of the group.
          type: string
          example: abc-123-def
        type:
          $ref: '#/components/schemas/SensitiveDataScannerGroupType'
      type: object
    SensitiveDataScannerGetConfigIncludedItem:
      description: An object related to the configuration.
      oneOf:
      - $ref: '#/components/schemas/SensitiveDataScannerRuleIncludedItem'
      - $ref: '#/components/schemas/SensitiveDataScannerGroupIncludedItem'
    SensitiveDataScannerRule:
      description: Rule item included in the group.
      properties:
        id:
          description: ID of the rule.
          type: string
          example: abc-123-def
        type:
          $ref: '#/components/schemas/SensitiveDataScannerRuleType'
      type: object
    SensitiveDataScannerGroupItem:
      description: Data related to a Sensitive Data Scanner Group.
      properties:
        id:
          description: ID of the group.
          type: string
          example: abc-123-def
        type:
          $ref: '#/components/schemas/SensitiveDataScannerGroupType'
      type: object
    SensitiveDataScannerGroupDeleteRequest:
      description: Delete group request.
      properties:
        meta:
          $ref: '#/components/schemas/SensitiveDataScannerMetaVersionOnly'
      required:
      - meta
      type: object
    SensitiveDataScannerRuleIncludedItem:
      description: A Scanning Rule included item.
      properties:
        attributes:
          $ref: '#/components/schemas/SensitiveDataScannerRuleAttributes'
        id:
          description: ID of the rule.
          type: string
          example: abc-123-def
        relationships:
          $ref: '#/components/schemas/SensitiveDataScannerRuleRelationships'
        type:
          $ref: '#/components/schemas/SensitiveDataScannerRuleType'
      type: object
    SensitiveDataScannerConfigurationRelationships:
      description: Relationships of the configuration.
      properties:
        groups:
          $ref: '#/components/schemas/SensitiveDataScannerGroupList'
      type: object
    SensitiveDataScannerRuleType:
      default: sensitive_data_scanner_rule
      description: Sensitive Data Scanner rule type.
      enum:
      - sensitive_data_scanner_rule
      example: sensitive_data_scanner_rule
      type: string
      x-enum-varnames:
      - SENSITIVE_DATA_SCANNER_RULE
    SensitiveDataScannerTextReplacement:
      description: Object describing how the scanned event will be replaced.
      properties:
        number_of_chars:
          description: 'Required if type == ''partial_replacement_from_beginning''

            or ''partial_replacement_from_end''. It must be > 0.'
          format: int64
          minimum: 0
          type: integer
          example: 42
        replacement_string:
          description: Required if type == 'replacement_string'.
          type: string
          example: example_value
        type:
          $ref: '#/components/schemas/SensitiveDataScannerTextReplacementType'
      type: object
    ExternalUserGroupPatchRequestOperationsItems:
      description: The definition of an individual patch operation in a patch request.
      properties:
        op:
          $ref: '#/components/schemas/ExternalUserGroupPatchRequestOperationsItemsOp'
        path:
          description: An attribute path describing the target of the operation.
          example: members
          type: string
        value:
          description: JSON element containing the target values required to apply the patch operation.
          example: "{\n    \"displayName\": \"Real new group\",\n    \"id\": \"80df3a9b-24f5-4ebf-9ba0-714455453621\"\n}"
      type: object
    SensitiveDataScannerFilter:
      description: Filter for the Scanning Group.
      properties:
        query:
          description: Query to filter the events.
          type: string
          example: avg:system.cpu.user{*}
      type: object
    SensitiveDataScannerGetConfigIncludedArray:
      description: Included objects from relationships.
      items:
        $ref: '#/components/schemas/SensitiveDataScannerGetConfigIncludedItem'
      type: array
    ListExternalUserGroupResponseResourcesItemsMembersItems:
      description: The definition of a member belonging to a group in the List groups response.
      properties:
        $ref:
          description: The URI corresponding to a resource that is a member of this group.
          example: https://app.datadoghq.com/api/scim/v2/Users/429ebce5-8ed3-4da9-9f1e-662f2dbc2fe6
          type: string
        display:
          description: Full name of the user.
          example: John Doe
          type: string
        type:
          description: A label indicating the type of resource. Only supported value is "User".
          example: User
          type: string
        value:
          description: The identifier of the member of this group.
          example: 429ebce5-8ed3-4da9-9f1e-662f2dbc2fe6
          type: string
      type: object
    SensitiveDataScannerGroupUpdate:
      description: Data related to the update of a group.
      properties:
        attributes:
          $ref: '#/components/schemas/SensitiveDataScannerGroupAttributes'
        id:
          description: ID of the group.
          type: string
          example: abc-123-def
        relationships:
          $ref: '#/components/schemas/SensitiveDataScannerGroupRelationships'
        type:
          $ref: '#/components/schemas/SensitiveDataScannerGroupType'
      type: object
  responses:
    TooManyRequestsResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/APIErrorResponse'
      description: Too many requests
    NotFoundResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/APIErrorResponse'
      description: Not Found
    BadRequestResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/APIErrorResponse'
      description: Bad Request
    ConflictResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/APIErrorResponse'
      description: Conflict
  parameters:
    SensitiveDataScannerGroupID:
      description: The ID of a group of rules.
      in: path
      name: group_id
      required: true
      schema:
        type: string
  securitySchemes:
    AuthZ:
      description: This API uses OAuth 2 with the implicit grant flow.
      flows:
        authorizationCode:
          authorizationUrl: /oauth2/v1/authorize
          scopes:
            apm_api_catalog_read: View API catalog and API definitions.
            apm_api_catalog_write: Add, modify, and delete API catalog definitions.
            apm_read: Read and query APM and Trace Analytics.
            apm_service_catalog_read: View service catalog and service definitions.
            apm_service_catalog_write: Add, modify, and delete service catalog definitions when those definitions are maintained by Datadog.
            appsec_vm_read: View infrastructure, application code, and library vulnerabilities. This does not restrict API or inventory SQL access to the vulnerability data source.
            cases_read: View Cases.
            cases_write: Create and update cases.
            ci_visibility_pipelines_write: Create CI Visibility pipeline spans using the API.
            ci_visibility_read: View CI Visibility.
            cloud_cost_management_read: View Cloud Cost pages and the cloud cost data source in dashboards and notebooks. For more details, see the Cloud Cost Management docs.
            cloud_cost_management_write: Configure cloud cost accounts and global customizations. For more details, see the Cloud Cost Management docs.
            code_analysis_read: View Code Analysis.
            continuous_profiler_pgo_read: Read and query Continuous Profiler data for Profile-Guided Optimization (PGO).
            create_webhooks: Create webhooks integrations.
            dashboards_embed_share: Create, modify, and delete shared dashboards with share type 'embed'.
            dashboards_invite_share: Create, modify, and delete shared dashboards with share type 'invite'.
            dashboards_public_share: Generate public and authenticated links to share dashboards or embeddable graphs externally.
            dashboards_read: View dashboards.
            dashboards_write: Create and change dashboards.
            data_scanner_read: View Data Scanner configurations.
            data_scanner_write: Edit Data Scanner configurations.
            embeddable_graphs_share: Generate public links to share embeddable graphs externally.
            events_read: Read Events data.
            hosts_read: List hosts and their attributes.
            incident_notification_settings_write: Configure Incidents Notification settings.
            incident_read: View incidents in Datadog.
            incident_settings_write: Configure Incident Settings.
            incident_write: Create, view, and manage incidents in Datadog.
            metrics_read: View custom metrics.
            monitor_config_policy_write: Edit and delete monitor configuration.
            monitors_downtime: Set downtimes to suppress alerts from any monitor in an organization. Mute and unmute monitors. The ability to write monitors is not required to set downtimes.
            monitors_read: View monitors.
            monitors_write: Edit, delete, and resolve individual monitors.
            org_management: Edit org configurations, including authentication and certain security preferences such as configuring SAML, renaming an org, configuring allowed login methods, creating child orgs, subscribing & unsubscribing from apps in the marketplace, and enabling & disabling Remote Configuration for the entire organization.
            security_comments_read: Read comments of vulnerabilities.
            security_monitoring_filters_read: Read Security Filters.
            security_monitoring_filters_write: Create, edit, and delete Security Filters.
            security_monitoring_findings_read: View a list of findings that include both misconfigurations and identity risks.
            security_monitoring_notification_profiles_read: View Rule Security Notification rules.
            security_monitoring_notification_profiles_write: Create, edit, and delete Security Notification rules.
            security_monitoring_rules_read: Read Detection Rules.
            security_monitoring_rules_write: Create and edit Detection Rules.
            security_monitoring_signals_read: View Security Signals.
            security_monitoring_suppressions_read: Read Rule Suppressions.
            security_monitoring_suppressions_write: Write Rule Suppressions.
            security_pipelines_read: View Security Pipelines.
            security_pipelines_write: Create, edit, and delete CSM Security Pipelines.
            slos_corrections: Apply, edit, and delete SLO status corrections. A user with this permission can make status corrections, even if they do not have permission to edit those SLOs.
            slos_read: View SLOs and status corrections.
            slos_write: Create, edit, and delete SLOs.
            synthetics_global_variable_read: View, search, and use Synthetics global variables.
            synthetics_global_variable_write: Create, edit, and delete global variables for Synthetics.
            synthetics_private_location_read: View, search, and use Synthetics private locations.
            synthetics_private_location_write: Create and delete private locations in addition to having access to the associated installation guidelines.
            synthetics_read: List and view configured Synthetic tests and test results.
            synthetics_write: Create, edit, and delete Synthetic tests.
            teams_manage: Manage Teams. Create, delete, rename, and edit metadata of all Teams. To control Team membership across all Teams, use the User Access Manage permission.
            teams_read: Read Teams data. A User with this permission can view Team names, metadata, and which Users are on each Team.
            test_optimization_read: View Test Optimization.
            timeseries_query: Query Timeseries data.
            usage_read: View your organization's usage and usage attribution.
            user_access_invite: Invite other users to your organization.
            user_access_manage: Disable users, manage user roles, manage SAML-to-role mappings, and configure logs restriction queries.
            user_access_read: View users and their roles and settings.
            workflows_read: View workflows.
            workflows_run: Run workflows.
            workflows_write: Create, edit, and delete workflows.
          tokenUrl: /oauth2/v1/token
      type: oauth2
    apiKeyAuth:
      description: Your Datadog API Key.
      in: header
      name: DD-API-KEY
      type: apiKey
      x-env-name: DD_API_KEY
    appKeyAuth:
      description: Your Datadog APP Key.
      in: header
      name: DD-APPLICATION-KEY
      type: apiKey
      x-env-name: DD_APP_KEY
    bearerAuth:
      scheme: bearer
      type: http
      x-env-name: DD_BEARER_TOKEN
x-group-parameters: true
x-merge-override:
  paths: false
